---
title: "Lab journal social networks"
author: "Lauren Dirix"
bibliography: references.bib
---

# Tutorial SNASS book
## A1 through A6 - Setting up
```{r}
rm(list = ls())

#install.packages("installr")
require(installr)
#install.packages("foreign")
require(foreign)
require(tidyverse)
updateR()
```

Loading datasets
``` {r}
cv08 <- foreign::read.spss("Cultural_Changes_2008.sav", use.value.labels = T, to.data.frame = T)
cv10 <- foreign::read.spss("Cultural_Changes_2010.sav", use.value.labels = T, to.data.frame = T)

cv08_nolab <- foreign::read.spss("Cultural_Changes_2008.sav", use.value.labels = F, to.data.frame = T)
cv10_nolab <- foreign::read.spss("Cultural_Changes_2010.sav", use.value.labels = F, to.data.frame = T)

cv08_haven <- haven::read_spss("Cultural_Changes_2008.sav")
cv10_haven <- haven::read_spss("Cultural_Changes_2010.sav")
```

Inspect the data
```{r}
str(cv08)
str(cv08_nolab)
str(cv08_haven)

str(cv08$lftop)
str(cv08_haven$lftop)

attributes(cv08$lftop)
attributes(cv08_nolab$lftop)
attributes(cv08_haven$lftop)

names(cv08_haven)
summary(cv08_haven)
head(cv08_haven)
fix(cv08)
View(cv08_haven)
```

## A7 - Assign missing values
### In base
```{r}
str(cv08_haven$lftop)
summary(cv08_haven$lftop)
attr(cv08_haven$lftop, "labels")
table(cv08_haven$lftop, useNA = "always")

cv08$lftop_new <- cv08$lftop
cv08$lftop_new[cv08$lftop_new == "Onbekend"] <- NA

table(cv08$lftop_new, useNA = "always")
levels(cv08$lftop_new)

cv08$agen <- as.numeric(as.character(cv08$lftop_new))
table(cv08$agen, useNA = "always")

str(cv08$agen)
```

### In tidy
```{r}
#cv08_haven <- mutate(cv08_haven, lftop_new = lftop)
#cv08_haven$lftop_new <- na_if(cv08_haven$lftop_new, 99)

#OR (more quickly)

cv08_haven <- mutate(cv08_haven, lftop_new = na_if(lftop, 99))

table(cv08_haven$lftop_new, useNA = "always")
```
## A8 - Recoding variables 
### In base
```{r}
levels(cv08$var006n)
table(cv08$var006n, useNA = "always")

cv08$educn <- as.numeric(cv08$var006n)
table(cv08$educn, useNA = "always")

cv08$educ3 <- NA

cv08$educ3[cv08$educn == 2 | cv08$educn ==3] <- 1
cv08$educ3[cv08$educn > 3 & cv08$educn < 8] <- 2
cv08$educ3[cv08$educn > 7 & cv08$educn < 11] <- 3

table(cv08$educ3, useNA = "always")
prop.table(table(cv08$educ3, useNA = "always"))

cv08$educ3 <- as.factor(cv08$educ3)
table(cv08$educ3, useNA = "always")

levels(cv08$educ3) <- c( "primary", "secondary", "tertiary")
table(cv08$educ3, useNA = "always")
```
### In tidy
```{r}
#install.packages("labelled")
require(labelled)

str(cv08_haven$var006n)
attr(cv08_haven$var006n, "labels")

table(cv08_haven$var006n, useNA = "always")

cv08_haven <- mutate(cv08_haven, educ3 = recode(var006n, '-3' = -9, '-1' = 1, '1' = 1, '2' = 2, '3' = 2, '4' = 2, '5' = 2, '6' = 3, '7' = 3, '8' = 3, '10' = -9), .keep_value_labels = FALSE)
cv08_haven <- mutate(cv08_haven, educ3 = na_if(educ3, -9))

cv08_haven <- mutate(cv08_haven, educ3 = factor(educ3, levels = c(1, 2, 3), labels = c("primary", "secondary", "tertiary")))

table(cv08_haven$educ3, useNA = "always")
```
Using piping
```{r}
cv08_haven <- cv08_haven %>%
  mutate(cv08_haven, educ3 = recode(var006n, '-3' = -9, '-1' = 1, '1' = 1, '2' = 2, '3' = 2, '4' = 2, '5' = 2, '6'
  = 3, '7' = 3, '8' = 3, '10' = -9), .keep_value_labels = FALSE) %>%
  mutate(educ3 = na_if(educ3, -9)) %>%
  mutate(educ3 = factor(educ3, levels = c(1, 2, 3), labels = c("primary", "secondary", "tertiary")))
```

## A9 - Means and counting
### In base
```{r}
summary(cv08$int055)
summary(cv08$int056)
summary(cv08$int057)

cv08$int055n <- as.numeric(cv08$int055)
table(cv08$int055n, useNA = "always")
cv08$int056n <- as.numeric(cv08$int056)
table(cv08$int056n, useNA = "always")
cv08$int057n <- as.numeric(cv08$int057)
table(cv08$int057n, useNA = "always")

cv08$int055n[cv08$int055n < 5] <- NA
cv08$int055n <- cv08$int055n - 4
cv08$int056n[cv08$int056n < 5] <- NA
cv08$int056n <- cv08$int056n - 4
cv08$int057n[cv08$int057n < 5] <- NA
cv08$int057n <- cv08$int057n - 4

#means per respondent
testmeans <- rowMeans(cbind(cv08$int055n, cv08$int056n, cv08$int057n), na.rm = T)
head(testmeans)

nmis <- rowSums(is.na(cbind(cv08$int055n, cv08$ubt056n, cv08$int057n)))
testmeans <- ifelse(nmis <2, testmeans, NA)
cv08$int_mean <- testmeans
```

### In tidy
```{r}
table(cv08_haven$int055, useNA = "always")
table(cv08_haven$int056, useNA = "always")
table(cv08_haven$int057, useNA = "always")

cv08_haven <- cv08_haven %>%
  mutate(int055n = recode(int055, '-6' = -9, '-5' = -9, '-3' = -9, '-2' = -9, '1' = 4, '2' = 3, '3'
    = 2, '4' = 1), .keep_value_labels = FALSE) %>%
  mutate(int055n = na_if(int055n, -9)) %>%
  mutate(int055n = labelled(int055n, c('Helemaal geen tegenstelling' = 1,'Niet zo groot' = 2, 'groot'
    = 3, 'Zeer groot' = 4)))
cv08_haven <- cv08_haven %>%
  mutate(int056n = recode(int056, '-6' = -9, '-5' = -9, '-3' = -9, '-2' = -9, '1' = 4, '2' = 3, '3'
    = 2, '4' = 1), .keep_value_labels = FALSE) %>%
  mutate(int056n = na_if(int056n, -9)) %>%
  mutate(int056n = labelled(int056n, c('Helemaal geen tegenstelling' = 1,'Niet zo groot' = 2, 'groot'
    = 3, 'Zeer groot' = 4)))
cv08_haven <- cv08_haven %>%
  mutate(int057n = recode(int057, '-6' = -9, '-5' = -9, '-3' = -9, '-2' = -9, '1' = 4, '2' = 3, '3'
    = 2, '4' = 1), .keep_value_labels = FALSE) %>%
  mutate(int057n = na_if(int057n, -9)) %>%
  mutate(int057n = labelled(int057n, c('Helemaal geen tegenstelling' = 1,'Niet zo groot' = 2, 'groot'
    = 3, 'Zeer groot' = 4)))

  #mean regardless of how many missings
cv08_haven <- cv08_haven %>%
  rowwise() %>%
  mutate(int_mean = mean(c(int055n, int056n, int057n), na.rm = TRUE))

  #mean with max 1 missing, otherwise NA
cv08_haven <- cv08_haven %>%
  mutate(int_mean_temp = rowMeans(cbind(int055n, int056n, int057n), na.rm = TRUE), nmis = 
    rowSums(is.na(cbind(int055n, int056n, int057n))), int_mean = ifelse(nmis < 2, int_mean_temp, 
    NA)) %>% 
  dplyr:: select(-int_mean_temp, -nmis)
```

## Merging data files
### In base
