---
title: "Lab journal social networks"
author: "Lauren Dirix"
bibliography: references.bib
---

# Preparation before class
```{r}
library("network")
library("sna")

load("./data/IndividualCharacteristics.RData")
load("./data/NetworkCharacteristics.RData")

# view(hanging[[1]])
hanging_df_t1 <- as.data.frame(hanging[[1]][1])
class(hanging_df_t1)
# view(hanging_df_t1)
strong_netw_t1 <- data.matrix(hanging_df_t1)
strong_netw_t1[strong_netw_t1==9]<-NA
class(strong_netw_t1)
# view(strong_netw_t1)

hanging_df_t2 <- as.data.frame(hanging[[1]][2])
class(hanging_df_t2)
# view(hanging_df_t2)
strong_netw_t2 <- data.matrix(hanging_df_t2)
strong_netw_t2[strong_netw_t2==9]<-NA
class(strong_netw_t2)
# view(strong_netw_t2)
```

<br>

## Descriptive statistics
### Density
```{r}
# Wave 1
netw1 <- as.network(strong_netw_t1)
network.density(netw1)
# 0.02720386

# Wave 2
netw2 <- as.network(strong_netw_t2)
network.density(netw2)
# 0.01859504
```
### Reciprocity
```{r}
#Wave 1
hangingw1_nona <- na_if(hanging[[1]][[1]], 9)
rowhangingw1 <- rowSums(is.na(hangingw1_nona)) == nrow(hangingw1_nona)
colhangingw1 <- colSums(is.na(hangingw1_nona)) == ncol(hangingw1_nona)
hangingw1_nona[which(rowhangingw1) , ] <- 0

g_strong_t1 <- igraph:: graph_from_adjacency_matrix(hangingw1_nona, mode = "directed")

reciprocity(g_strong_t1, ignore.loops = TRUE, mode = c("default", "ratio"))
# 0.4708861

# Wave 2
hangingw2_nona <- na_if(hanging[[1]][[2]], 9)
rowhangingw2 <- rowSums(is.na(hangingw2_nona)) == nrow(hangingw2_nona)
colhangingw2 <- colSums(is.na(hangingw2_nona)) == ncol(hangingw2_nona)
hangingw2_nona[which(rowhangingw2) , ] <- 0

g_strong_t2 <- igraph:: graph_from_adjacency_matrix(hangingw2_nona, mode = "directed")

reciprocity(g_strong_t2, ignore.loops = TRUE, mode = c("default", "ratio"))
# 0.4444444
```

### Dyad configurations
```{r}
# Wave 1
dyad_census(g_strong_t1)
# Mutual ties: 93
# Asymmetrical ties: 209
# No tie: 6958

# Wave 2
dyad_census(g_strong_t2)
# Mutual ties: 60
# Asymmetrical ties: 150
# No tie: 7050
```
### Triad configurations
```{r}
# Wave 1
triad_census(g_strong_t1)
# 003 = 253808
# 012 = 22549
# 102 = 10101
# 021D = 235
# 021U = 243
# 021C = 219
# 111D = 247
# 111U = 254
# 030T = 61
# 030C = 2
# 201 = 80
# 120D = 40
# 120U = 54
# 120C = 2
# 210 = 46
# 300 = 39

# Wave 2
triad_census(g_strong_t2)
# 003 = 263853
# 012 = 16659
# 102 = 6713
# 021D = 133
# 021U = 125
# 021C = 123
# 111D = 88
# 111U = 132
# 030T = 30
# 030C = 0
# 201 = 46
# 120D = 9
# 120U = 39
# 120C = 2
# 210 = 19
# 300 = 9
```
### Transitivity
```{r}
# Wave 1
transitivity(g_strong_t1)
# 0.3641791

# Wave 2
transitivity(g_strong_t2)
# 0.3336766
```
### Path length
```{r}
# Wave 1
mean((ego_size(g_strong_t1, order = 2, mode = "out") - 1)/vcount(g_strong_t1))
# 0.07820504

# Wave 2
mean((ego_size(g_strong_t2, order = 2, mode = "out") - 1)/vcount(g_strong_t2))
# 0.0458302
```
### Segregation
To be calculated when I get my dependent variable of interest :)
```{r}

```